mutation clearNotificationsForDispute($disputeId: ID!) {
  markNotificationsAsReadForDispute(disputeId: $disputeId) {
    updatedNotification {
      id
      read
    }
    notificationStatus {
      totalCountUnread
    }
  }
}
