query getDispute($disputeId: ID!) {
  dispute(id: $disputeId) {
    id
    subject {
      id
      subject
      tweetId
      disputes {
        id
        partnerA {
          id
          name
        }
        partnerB {
          id
          name
        }
      }
    }
    ...ChatDispute
  }
  me {
    ...ChatPerson
  }
}
