query getDispute($disputeId: ID!) {
  dispute(id: $disputeId) {
    ...Dispute
  }
  me {
    ...ChatPerson
  }
}

fragment Dispute on Dispute {
  id
  subject {
    id
    subject
    tweetId
    disputes {
      id
      partnerA {
        id
        name
      }
      partnerB {
        id
        name
      }
    }
  }
  ...ChatDispute
}
