mutation replyOnDispute($disputeId: ID!, $message: String!) {
  replyOnDispute(input: { disputeId: $disputeId, message: $message }) {
    id
    messages {
      id
      author {
        id
      }
      text
    }
    lastUpdateAt
  }
}
