query ChatList($after: DateTime, $before: DateTime, $search: String) {
  chat(after: $after, before: $before, search: $search) {
    items {
      ...ChatListItem
    }
    newestLastUpdateAt
    oldestLastUpdateAt
    hasNextPage
  }
}

fragment ChatListItem on ChatItem {
  id
  lastUpdateAt
  ... on Dispute {
    createdAt
    subject {
      id
      subject
    }
    partnerA {
      ...ChatPerson
    }
    partnerB {
      ...ChatPerson
    }
  }
  ... on Subject {
    author {
      ...ChatPerson
    }
    subjectTitle: subject
  }
}
