query ChatList($after: DateTime, $before: DateTime) {
  chat(after: $after, before: $before) {
    items {
      ...ChatListItem
    }
    newestLastMessageAt
    oldestLastMessageAt
    hasNextPage
  }
}

fragment ChatListItem on Dispute {
  id
  createdAt
  lastMessageAt
  subject {
    id
    subject
  }
  partnerA {
    ...ChatPerson
  }
  partnerB {
    ...ChatPerson
  }
}
