query TwitterTimeline($after: String) {
  twitterTimeline(after: $after) {
    edges {
      cursor
      node {
        id
        link
      }
    }
    pageInfo {
      startCursor
      endCursor
    }
  }
}
