query ChatItem($id: ID!) {
  chatItem(id: $id) {
    id
    ...Dispute
    ...Subject
  }
  me {
    ...ChatPerson
  }
}

fragment Dispute on Dispute {
  id
  subject {
    id
    subject
    tweetId
  }
  ...ChatDispute
}

fragment Subject on Subject {
  id
  topic: subject
  tweetId
  ...ChatSubject
}
