fragment ChatSubject on Subject {
  id
  author {
    ...ChatPerson
  }
  firstMessage {
    ...ChatMessage
  }
  createdAt
}

fragment ChatDispute on Dispute {
  id
  partnerA {
    ...ChatPerson
  }
  partnerB {
    ...ChatPerson
  }
  messages {
    ...ChatMessage
  }
}

fragment ChatMessage on Message {
  id
  text
  createdAt
  author {
    ...ChatPerson
  }
  votes {
    ...MessageVotes
  }
}

fragment ChatPerson on User {
  id
  name
  twitterHandle
  picture
}

fragment MessageVotes on Votes {
  ups
  downs
  userVoting
}
