fragment ChatSubject on Subject {
  id
  author {
    ...ChatPerson
  }
  firstMessage {
    text
  }
  createdAt
}

fragment ChatDispute on Dispute {
  id
  partnerA {
    ...ChatPerson
  }
  partnerB {
    ...ChatPerson
  }
  messages {
    ...ChatMessage
  }
}

fragment ChatMessage on Message {
  id
  text
  createdAt
  author {
    id
    name
    picture
  }
}

fragment ChatPerson on User {
  id
  name
  picture
}
