query me {
  me {
    ...ChatPerson
  }
}

mutation createSubject(
  $subject: String!
  $tweetId: String
  $firstMessage: String!
) {
  createSubject(
    input: { subject: $subject, tweetId: $tweetId, firstMessage: $firstMessage }
  ) {
    id
    subject
    tweetId
  }
}
