query getAllSubjects {
  allSubjects {
    edges {
      node {
        id
        subject
        author {
          name
        }
        disputes {
          id
          partnerB {
            name
          }
        }
      }
    }
  }
}
