query getAllSubjects($cursor: String) {
  allSubjects(limit: 20, after: $cursor) {
    edges {
      node {
        id
        subject
        author {
          name
        }
        disputes {
          id
          partnerB {
            name
          }
        }
      }
    }
    pageInfo {
      hasNextPage
      endCursor
    }
  }
}
