query getSubject($subjectId: ID!) {
  subject(id: $subjectId) {
    id
    subject
    tweetId
    ...ChatSubject
    disputes {
      id
      partnerB {
        id
        name
      }
    }
  }
  me {
    ...ChatPerson
  }
}
