query getSubject($subjectId: ID!) {
  subject(id: $subjectId) {
    id
    subject
    tweetId
    author {
      id
      name
      picture
    }
    firstMessage {
      id
      text
    }
  }
  me {
    id
    name
    picture
  }
}
