query NotificationList($after: String, $before: String) {
  notificationStatus {
    totalCountUnread
  }
  allNotifications(first: 10, last: 10, after: $after, before: $before) {
    totalCount
    pageInfo {
      hasNextPage
      startCursor
      endCursor
    }
    edges {
      node {
        id
        createdAt
        read
        __typename
        ... on NewMessageNotification {
          message {
            id
            author {
              ...ChatPerson
            }
            dispute {
              id
            }
          }
        }
        ... on NewDisputeNotification {
          dispute {
            id
            partnerB {
              ...ChatPerson
            }
          }
        }
      }
    }
  }
}
