query getAllDisputes($cursor: String) {
  allDisputes(first: 20, after: $cursor) {
    edges {
      node {
        id
        lastMessageAt
        subject {
          id
          subject
        }
        partnerA {
          id
          name
        }
        partnerB {
          id
          name
        }
      }
    }
    pageInfo {
      endCursor
      hasNextPage
    }
  }
}
