query ChatItemHeader($chatItemId: ID!) {
  chatItem(id: $chatItemId) {
    ...SubjectInHeader
    ... on Dispute {
      id
      subject {
        ...SubjectInHeader
      }
    }
  }
}

fragment SubjectInHeader on Subject {
  id
  topic: subject
  disputes {
    ...DisputeInHeader
  }
}

fragment DisputeInHeader on Dispute {
  id
  partnerA {
    id
    name
  }
  partnerB {
    id
    name
  }
}
